#!/bin/bash
###### Openstack-Ocata-Neutron_VXLAN-Ubuntu-16.04-SVK-GIT-Mar-2017 #######
#################################################
#Network-Node-Installation#
#################################################
Node_Inst_Start () {
	echo -e  "######\e[92m Starting ---- $1 ---- Installation \e[0m######"
	echo -e "#####\e[31m Update and Upgrade the Server Before starting the Installation \e[0m#####"
	sleep 2
	read -rsp $' ... If Updated \e[92mPress any key\e[0m to Continue OR \e[31mCTRL+C\e[0m to Exit Installation ... \n' -n1 key
}
Key_To_Start () {
	read -rsp $' ... \e[92mPress any key\e[0m to Continue OR \e[31mCTRL+C\e[0m to Exit Installation ... \n' -n1 key
}
config_of () {
	echo -e "############  \e[96mConfiguration of \e[0m \e[93m$1\e[0m  ############"
}
Openstack_Service_Inst () {
	echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
	echo -e "############  \e[93m$1 Configuration Completed\e[0m  ############\n"
	echo -e "     ...\e[92mPress any key\e[0m ...To Start \e[96m $2 \e[0m Configuration ...     "
	sleep 2
	read -n1 key
	echo -e "############  \e[96m-----Configuring---$2-----\e[0m  ############"
}
Complete_Reboot () {
	echo -e "############  \e[92m---Installation Completed----\e[0m  ############"
	echo -e "##### ...\e[93m Access the dashboard using a web browser: \e[0m--- \e[96mhttp://$con_ip/horizon\e[0m ...#####"
	sleep 2
	read -rsp $'\e[1;97;45m     ...Press any key to Exit...and...Reboot The Sever After Exit...     \e[0m\n' -n1 key
}
#################################################
Node_Inst_Start Network-Node
sed -i '/network\|controller\|compute/d' /etc/hosts
echo -e " ##### \e[93mSet OPenstack-Host-IP'S\e[0m ##### "
sleep 2
echo -en "\e[92m Controller-Node IP : \e[0m"
read con_ip
echo -en "\e[92m Network-Node IP : \e[0m"
read net_ip
echo -en "\e[92m Compute-Node IP : \e[0m"
read com_ip
echo -n "External Bridge ,Device which has Manual Settings/No-IP(e.g, eth1/eth2..etc) :"
read extdev
echo -e "$con_ip 	controller\n$net_ip 	network\n$com_ip 	compute\n " >> /etc/hosts
echo -e "###### \e[92mStarting Installation\e[0m ######"
Key_To_Start
sleep 3
apt install -y curl wget
sleep 3
apt -y install software-properties-common
sleep 2
add-apt-repository cloud-archive:ocata
sleep 2
apt update 
sleep 3
apt install -y chrony
apt install -y python-pymysql python-openstackclient
apt install -y neutron-plugin-ml2 neutron-plugin-linuxbridge-agent neutron-l3-agent neutron-dhcp-agent neutron-metadata-agent python-neutronclient
echo -e "######\e[96m  Enable IP Forwarding  \e[0m######"
cp /etc/sysctl.conf /etc/sysctl.conf.org
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Network/sysctl.conf > /etc/sysctl.conf
sleep 3
sysctl -p
sleep 3
echo -e "######\e[93m Installed Various Openstack-Packages on Network Node\e[0m ######"
######Configuration of Chrony-NTP-Server#######
sleep 2
config_of Chrony-NTP-Server
sleep 2
Key_To_Start
sleep 2
sleep 1
cp /etc/chrony/chrony.conf /etc/chrony/chrony.conf.org
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Network/chrony.conf > /etc/chrony/chrony.conf
sleep 3
systemctl restart chrony 
sleep 2
chronyc sources
sleep 3
##########################################################
#NEUTRON Installation
##########################################################
Openstack_Service_Inst Basic-System NEUTRON
sleep 1
cp /etc/neutron/neutron.conf /etc/neutron/neutron.conf.org
cp /etc/neutron/l3_agent.ini /etc/neutron/l3_agent.ini.org
cp /etc/neutron/dhcp_agent.ini /etc/neutron/dhcp_agent.ini.org
cp /etc/neutron/metadata_agent.ini /etc/neutron/metadata_agent.ini.org
cp /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugins/ml2/ml2_conf.ini.org
cp /etc/neutron/plugins/ml2/linuxbridge_agent.ini /etc/neutron/plugins/ml2/linuxbridge_agent.ini.org
sleep 3
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Network/neutron.conf > /etc/neutron/neutron.conf
sleep 3
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Network/l3_agent.ini > /etc/neutron/l3_agent.ini
sleep 3
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Network/dhcp_agent.ini > /etc/neutron/dhcp_agent.ini
sleep 3
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Network/dnsmasq-neutron.conf > /etc/neutron/dnsmasq-neutron.conf
sleep 3
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Network/metadata_agent.ini > /etc/neutron/metadata_agent.ini
sleep 3
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Network/ml2_conf.ini > /etc/neutron/plugins/ml2/ml2_conf.ini 
sleep 3
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Network/linuxbridge_agent.ini > /etc/neutron/plugins/ml2/linuxbridge_agent.ini
sleep 3
sed -i "s/\$extdev/${extdev}/g" /etc/neutron/plugins/ml2/linuxbridge_agent.ini
sed -i "s/\$tunnel_ip/${net_ip}/g" /etc/neutron/plugins/ml2/linuxbridge_agent.ini
sleep 3
ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini 
echo -e " ########## \e[96m--------Configuring---------Bridge---------\e[0m ##########"
sleep 2
read -rsp $'\n... \e[31mEdit /etc/network/interfaces file using Another Terminal to configure bridge \e[0m...\n\n\e[0m... IF done ...\e[92mPress Any Key\e[0m to Continue installation ...\n' -n1 key
sleep 3
systemctl restart neutron-l3-agent 
sleep 3
systemctl restart  neutron-dhcp-agent
sleep 3
systemctl restart  neutron-metadata-agent
sleep 3
systemctl restart  neutron-linuxbridge-agent
sleep 3
echo -e 'export OS_PROJECT_DOMAIN_NAME=default
export OS_USER_DOMAIN_NAME=default
export OS_PROJECT_NAME=admin
export OS_TENANT_NAME=admin
export OS_USERNAME=admin
export OS_PASSWORD=0penstack
export OS_AUTH_URL=http://controller:35357/v3
export OS_IDENTITY_API_VERSION=3
export OS_IMAGE_API_VERSION=2
export OS_VOLUME_API_VERSION=2'>/root/adminrc
sleep 2
source /root/adminrc
sleep 3
echo "source /root/adminrc" >> /root/.bashrc
sleep 3
echo -e "#########\e[1;95m openstack network agent list \e[0m#########"
openstack network agent list
sleep 3
#####    Local Script For Checking Openstack Logs and Service Status    #####
echo -e "###\e[96m Creating Local Script For Checking Openstack Logs and Service Status \e[0m ###"
echo -e 'for i in neutron-{l3-agent,dhcp-agent,metadata-agent,linuxbridge-agent}\ndo\nsystemctl $1 $i\ndone' > /root/opser.sh
chmod +x /root/opser.sh
sleep 3
/root/opser.sh enable 
sleep 3
echo -e 'for i in $(ls /var/log/neutron/*)\ndo\n>$i\ndone' > /root/cleanlog.sh
chmod +x /root/cleanlog.sh
echo -e 'grep -i error /var/log/neutron/*.log ' > /root/errlogcheck
chmod +x /root/errlogcheck
sleep 3
echo 'egrep -v "^\s*#|^$" $1 $2' > /bin/uv 
chmod +x /bin/uv
Complete_Reboot
sleep 3
exit
##########################################################
##########################################################

