#!/bin/bash
##### Openstack-Ocata-Neutron_VXLAN-Ubuntu-16.04-SVK-GIT-Mar-2017 ######
#################################################
#Compute-Node-Installation#
#################################################
Node_Inst_Start () {
	echo -e  "######\e[92m Starting ---- $1 ---- Installation \e[0m######"
	echo -e "#####\e[31m Update and Upgrade the Server Before starting the Installation \e[0m#####"
	sleep 2
	read -rsp $' ... If Updated \e[92mPress any key\e[0m to Continue OR \e[31mCTRL+C\e[0m to Exit Installation ... \n' -n1 key
}
Key_To_Start () {
	read -rsp $' ... \e[92mPress any key\e[0m to Continue OR \e[31mCTRL+C\e[0m to Exit Installation ... \n' -n1 key
}
config_of () {
	echo -e "############  \e[96mConfiguration of \e[0m \e[93m$1\e[0m  ############"
}
Openstack_Service_Inst () {
	echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
	echo -e "############  \e[93m$1 Configuration Completed\e[0m  ############\n"
	echo -e "     ...\e[92mPress any key\e[0m ...To Start \e[96m $2 \e[0m Configuration ...     "
	sleep 2
	read -n1 key
	echo -e "############  \e[96m-----Configuring---$2-----\e[0m  ############"
}
Complete_Reboot () {
	echo -e "############  \e[92m---Installation Completed----\e[0m  ############"
	echo -e "##### ...\e[93m Access the dashboard using a web browser: \e[0m--- \e[96mhttp://$con_ip/horizon\e[0m ...#####"
	sleep 2
	read -rsp $'\e[1;97;45m     ...Press any key to Exit...and...Reboot The Sever After Exit...     \e[0m\n' -n1 key
}
#################################################
Node_Inst_Start Compute-Node
sed -i '/network\|controller\|compute/d' /etc/hosts
echo -e " ##### \e[93mSet OPenstack-Host-IP'S\e[0m ##### "
sleep 2
echo -en "\e[92m Controller-Node IP : \e[0m"
read con_ip
echo -en "\e[92m Network-Node IP : \e[0m"
read net_ip
echo -en "\e[92m Compute-Node IP : \e[0m"
read com_ip
echo -n "External Bridge ,Device which has Manual Settings/No-IP(e.g, eth1/eth2..etc) :"
read extdev
echo -e "$con_ip 	controller\n$net_ip 	network\n$com_ip 	compute\n " >> /etc/hosts
echo -e '###### \e[92mStarting Installation\e[0m ######'
Key_To_Start
sleep 3
sleep 3
apt -y install software-properties-common
sleep 2
add-apt-repository cloud-archive:ocata
sleep 2
apt update 
sleep 2
apt install -y curl wget
apt install -y chrony python-pymysql python-openstackclient 
apt install -y nova-compute-kvm python-novaclient neutron-common neutron-plugin-ml2 neutron-plugin-linuxbridge-agent 
echo -e "######\e[93m Installed Various Openstack-Packages on Compute Node\e[0m ######"
sleep 2
echo -e "######\e[96m  Enable IP Forwarding  \e[0m######"
sleep 2
Key_To_Start
sleep 1
cp /etc/sysctl.conf /etc/sysctl.conf.org
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Compute/sysctl.conf > /etc/sysctl.conf
sleep 2
sysctl -p
######  Configuratin of Chrony-NTP-Server  ##########
config_of Chrony-NTP-Server
cp /etc/chrony/chrony.conf /etc/chrony/chrony.conf.org
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Compute/chrony.conf > /etc/chrony/chrony.conf
sleep 3
systemctl restart chrony 
sleep 3
chronyc sources
#######################################################
#COMPUTE Installation
#######################################################
Openstack_Service_Inst Basic-System NOVA
sleep 1
cp /etc/nova/nova.conf /etc/nova/nova.conf.org
cp /etc/nova/nova-compute.conf /etc/nova/nova-compute.conf.org
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Compute/nova.conf > /etc/nova/nova.conf
sed -i "s/\$com_ip/${com_ip}/g" /etc/nova/nova.conf
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Compute/nova-compute.conf > /etc/nova/nova-compute.conf
sleep 2
cp /etc/neutron/neutron.conf /etc/neutron/neutron.conf.org 
cp /etc/neutron/plugins/ml2/ml2_conf.ini  /etc/neutron/plugins/ml2/ml2_conf.ini.org 
cp /etc/neutron/plugins/ml2/linuxbridge_agent.ini /etc/neutron/plugins/ml2/linuxbridge_agent.ini.org
sleep 2
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Compute/neutron.conf > /etc/neutron/neutron.conf
sleep 2
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Compute/ml2_conf.ini  > /etc/neutron/plugins/ml2/ml2_conf.ini 
sleep 3
curl https://raw.githubusercontent.com/cloudofsvk/OPS-Latest/Ocata/neutron-network-ub16/Compute/linuxbridge_agent.ini > /etc/neutron/plugins/ml2/linuxbridge_agent.ini
sleep 3
sed -i "s/\$extdev/${extdev}/g" /etc/neutron/plugins/ml2/linuxbridge_agent.ini
sed -i "s/\$tunnel_ip/${com_ip}/g" /etc/neutron/plugins/ml2/linuxbridge_agent.ini
sleep 2
ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini 
sleep 2
rm -rf /var/lib/nova/nova.sqlite
sleep 2
systemctl restart nova-compute neutron-linuxbridge-agent 
sleep 3
echo -e 'export OS_PROJECT_DOMAIN_NAME=default
export OS_USER_DOMAIN_NAME=default
export OS_PROJECT_NAME=admin
export OS_USERNAME=admin
export OS_PASSWORD=0penstack
export OS_AUTH_URL=http://controller:35357/v3
export OS_IDENTITY_API_VERSION=3
export OS_IMAGE_API_VERSION=2
export OS_VOLUME_API_VERSION=2'>/root/adminrc
sleep 2
source /root/adminrc
sleep 3
echo "source /root/adminrc" >> /root/.bashrc
sleep 2
echo -e "#########\e[1;95m openstack compute service list \e[0m#########"
openstack compute service list
sleep 3
echo -e "######\e[31m  Deleting Default Virtual Net of KVM Service  \e[0m######" 
sleep 2
Key_To_Start
sleep 2
virsh net-list
sleep 2
virsh net-autostart default --disable
sleep 2
virsh net-destroy default
sleep 2
#####    Local Script For Checking Openstack Logs and Service Status    #####
echo -e "###\e[96m Creating Local Script For Checking Openstack Logs and Service Status \e[0m###"
echo -e 'for i in nova-compute neutron-linuxbridge-agent\ndo\n systemctl $1 $i\ndone' > /root/opser.sh
chmod +x /root/opser.sh
sleep 3
echo -e 'for i in $(ls /var/log/{neutron,nova}/*)\ndo\n>$i\ndone'> /root/cleanlog.sh
chmod +x /root/cleanlog.sh
sleep 3
echo -e 'grep -i error /var/log/{neutron,nova}/*.log ' > /root/errlogcheck
chmod +x /root/errlogcheck
sleep 3
echo 'egrep -v "^\s*#|^$" $1 $2' > /bin/uv
chmod +x /bin/uv
Complete_Reboot
sleep 3
exit
##########################################################
##########################################################
